### PR TITLE
Create .gitattributes

### PR DESCRIPTION
**Pull request by erikn69**

### CODE REVIEW

**Comment by erikn69** [comment]
@corbosman also on master branch `.gitattributes` is missing

**Comment by erikn69** [comment]
Failing tests maybe related `https://github.com/thephpleague/oauth2-server/pull/1282`

**Comment by corbosman** [comment]
Yes I already merged your gitattributes to master yesterday but ran into failing tests. I figured out why, i'll push the code today. It's because I was using minimum stability dev and it was pulling in a broken dev version of passport for the tests.

**Comment by corbosman** [comment]
Oh and yes, it most likely is because of what that PR is fixing. It's a problem in league code that I can't really fix but that passport has to deal with.

**Comment by corbosman** [comment]
Hi, I pushed a 3.0.3 and a 4.0.1 with gitattributes, thanks for the PR.

**Pull request merged**
