### PR TITLE
Support issuer ( iss )claim

### PR DESCRIPTION
**Pull request by abublihi**
in response of #32

### CODE REVIEW

**Comment by corbosman** [comment]
Sorry I've been traveling. Would it be an idea to only use 1 parameter? Just call it 'issuer', and let the config say:

```
'issuer' => env('JWT_ISSUER', null)
```

And the code checks for not null?

**Comment by abublihi** [comment]
I want to make sure the configuration are more readable, what i mean setting the iss may not mean the iss should be included but also you have to enable it, because it's additional not required, some programmer may confuse that they should set it.

**Comment by corbosman** [comment]
I don't think people will get confused. Laravel is full of settings where it's either null or set.  Having 2 settings means more code to check if it's enabled but not set properly. I would really prefer just env('JWT_ISSUER', null). You could add a comment to the config file saying it should be null, and you could even comment out the whole setting by default. This package has existed for quite a few years and no one ever asked for iss before. It's a very niche thing to need so I don't think many people will get confused. If you look at the https://github.com/corbosman/laravel-passport-claims/pull/33 , you might even just do what they ended up doing. It's pretty easy nowadays to add your own AccessToken. Then you don't even need my package.

**Comment by abublihi** [comment]
I know that i can implement my own AccessToken, but for the sake of simplicity i am adding the iss to this package, 

now only one setting for the issuer,

**Comment by corbosman** [comment]
Thanks for the PR, i pushed a 5.3.0 version including your code.

**Pull request merged**
